name: Test MSDS630 hw3

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3
      uses: actions/setup-python@v2
    - name: Install libs
      run: |
        pip install --upgrade pip
        pip install torch==1.13.0+cpu torchvision==0.1.6 -f https://download.pytorch.org/whl/torch_stable.html
        pip install pytest
        pip install numpy
        pip install pandas
        pip install scikit-learn
    - name: Test with pytest
      run: |
        pytest test_adaboost.py
